version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/Denver
      WATCHTOWER_CLEANUP: true
      # Schedule definition. Leaving this off will default to using a poll interval of 24hrs. See https://containrrr.dev/watchtower/arguments/#poll_interval.
      WATCHTOWER_SCHEDULE: "0 0 5 * * SAT"  # Run every Saturday at 5:00am
      # Settings for notifications
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: ${NOTIFICATIONS_HOSTNAME}
      # Additional notification URLs can be added to this list (space separated), if desired.
      # See https://containrrr.dev/watchtower/notifications/#shoutrrr_notifications for instructions.
      # See https://containrrr.dev/shoutrrr/v0.8/services/overview/ for a list of available options.
      # Email URL:
      # smtp://${EMAIL_SENDER}:${EMAIL_SENDER_PASS}@smtp.gmail.com:465/?from=${EMAIL_SENDER}&to=${DEST_EMAIL}&fromName=Shoutrrr
      WATCHTOWER_NOTIFICATION_URL: >
        pushover://shoutrrr:${PUSHOVER_API_TOKEN}@${PUSHOVER_USER_KEY}
    restart: always
