services:
  telegraf-eaton-server-room:
    image: telegraf
    container_name: telegraf-eaton-server-room
    restart: always
    environment:
      - INFLUX_TOKEN=${EATON_SERVER_ROOM_INFLUX_TOKEN}
      - SNMP_PASSWORD=${EATON_SERVER_ROOM_SNMP_PASSWORD}
    volumes:
      - /home/zbrewer/telegraf/eaton-server-room-telegraf.conf:/etc/telegraf/telegraf.conf:ro

  telegraf-apc-network-shelf:
    image: telegraf
    container_name: telegraf-apc-network-shelf
    restart: always
    environment:
      - INFLUX_TOKEN=${APC_NETWORK_SHELF_INFLUX_TOKEN}
      - NUT_USERNAME=${APC_NETWORK_SHELF_NUT_USERNAME}
      - NUT_PASSWORD=${APC_NETWORK_SHELF_NUT_PASSWORD}
    volumes:
      - /home/zbrewer/telegraf/apc-network-shelf.conf:/etc/telegraf/telegraf.conf:ro

  telegraf-truenas:
    image: telegraf
    container_name: telegraf-truenas
    restart: always
    ports:
      - 8094:8094
    environment:
      - INFLUX_TOKEN=${TRUENAS_INFLUX_TOKEN}
    volumes:
      - /home/zbrewer/telegraf/truenas.conf:/etc/telegraf/telegraf.conf:ro

  telegraf-truenas-backup:
    image: telegraf
    container_name: telegraf-truenas-backup
    restart: always
    ports:
      - 8095:8095
    environment:
      - INFLUX_TOKEN=${TRUENAS_BACKUP_INFLUX_TOKEN}
    volumes:
      - /home/zbrewer/telegraf/truenas-backup.conf:/etc/telegraf/telegraf.conf:ro
