services:
  hamclock:
    image: ghcr.io/chrisromp/hamclock-docker:latest
    ports:
      - "8100:8080/tcp"
      - "8101:8081/tcp"
    volumes:
      - data:/root/.hamclock
    restart: unless-stopped

volumes:
  data:
