version: '3'

networks:
  guacamole_network:
    driver: bridge

services:
  postgres:
    container_name: postgres_guacamole
    image: postgres
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: <password>
      POSTGRES_USER: guacamole_user
    networks:
      guacamole_network:
    volumes:
      - ./init/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/postgresql/data:rw

  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      guacamole_network:
    restart: unless-stopped
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw

  guacamole:
    container_name: guacamole
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: <password>
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    links:
      - guacd
    networks:
      guacamole_network:
    ports:
      - 8080:8080/tcp
    restart: unless-stopped
