services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    restart: unless-stopped
    environment:
    - PRIMARY=http://10.0.10.11|${PRIMARY_PASSWORD}
    - REPLICAS=http://10.0.10.12|${BACKUP_PASSWORD}
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=0 * * * *
    - TZ=America/Denver
