version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3030:3000
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=10.0.10.31:3030,homepage.brew.foo
    volumes:
      - /home/zbrewer/homepage/config:/app/config
      - /home/zbrewer/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
