services:
  arm-rippers:
    image: automaticrippingmachine/automatic-ripping-machine:latest
    container_name: arm-rippers
    restart: unless-stopped
    cpuset: 1,2,3
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /home/arm:/home/arm
      - /home/arm/logs:/home/arm/logs
      - /mnt/media:/home/arm/media
      - /home/arm/config:/etc/arm/config
    devices:
      - /dev/sr1:/dev/sr1
