---

- hosts: codeserver
  become: yes
  vars_files: ~/ansible/vault_vars.yml
  tasks:

  - name: Run Codeserver Update Script
    ansible.builtin.shell: curl -fsSL https://code-server.dev/install.sh | sh

  - name: Reload Codeserver
    ansible.builtin.systemd:
      daemon_reload: yes
      name: code-server@{{ ansible_env.USER }}
      state: restarted
