---

- hosts: pihole
  become: yes
  vars_files: ~/ansible/vault_vars.yml
  tasks:

  - name: Update Pi-Hole and Gravity if needed
    ansible_pihole:
      update_pihole: yes
      update_gravity: yes
