{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Outside Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"outside_environmental_sensor_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Upstairs Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"bedroom_environmental_sensor_temperature\" or r[\"entity_id\"] == \"living_room_current_temperature\" or r[\"entity_id\"] == \"main_floor_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Basement Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"basement_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Server Room Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"server_room_environment_sensor_temperature\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"Server Room Environment Sensor Temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Current Power Use",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"W\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"xcel_itron_5_instantaneous_demand_value\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 1m)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Outside Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"outside_environmental_sensor_humidity\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Upstairs Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"living_room_current_humidity\" or r[\"entity_id\"] == \"bedroom_environmental_sensor_humidity\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Server Room Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"server_room_environment_sensor_humidity\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Historical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 15m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"living_room_current_humidity\" or r[\"entity_id\"] == \"bedroom_environmental_sensor_humidity\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 15m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"outside_environmental_sensor_humidity\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 1m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"W\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 1m)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"eaton-5px2200rt\")\r\n  |> range(start: date.sub(d: 1m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"output_load_percent\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 1m)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 15m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"bedroom_environmental_sensor_temperature\" or r[\"entity_id\"] == \"living_room_current_temperature\" or r[\"entity_id\"] == \"main_floor_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 15m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"basement_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 15m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"outside_environmental_sensor_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Upstairs Temperature Difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 15m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"bedroom_environmental_sensor_temperature\" or r[\"entity_id\"] == \"living_room_current_temperature\" or r[\"entity_id\"] == \"main_floor_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 15m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"basement_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Upstairs Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 15m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"bedroom_environmental_sensor_temperature\" or r[\"entity_id\"] == \"living_room_current_temperature\" or r[\"entity_id\"] == \"main_floor_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Downstairs Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 15m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"basement_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Inside Temperature Difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 15m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"bedroom_environmental_sensor_temperature\" or r[\"entity_id\"] == \"living_room_current_temperature\" or r[\"entity_id\"] == \"main_floor_temperature\" or r[\"entity_id\"] == \"basement_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 15m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"outside_environmental_sensor_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Outside Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"interpolate\"\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: date.sub(d: 15m, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°F\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"outside_environmental_sensor_temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> interpolate.linear(every: 15m)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}