version: '3'
services:
  firefox:
    image: jlesage/firefox
    container_name: firefox
    restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - ./data:/config:rw
    environment:
      - TZ=America/Denver
      - SECURE_CONNECTION=1
